### ISSUE TITLE
倒入库之后  按照您的方法 一直提示找不见Echo这个类

### ISSUE THREAD

**Issue by LIErCai** [val-bubbleflat/laravel-echo-ios#1]
![2017-12-20 9 54 13](https://user-images.githubusercontent.com/17564380/34210294-5a46d224-e5d0-11e7-897d-8495282217a0.png)

**Comment by ghost** [comment]
I have the same problem. Any idea?

**Comment by ghost** [comment]
is this issue already fix?

can someone comment the solution? thanks
