### ISSUE TITLE
Unable to connect to the socket

### ISSUE THREAD

**Issue by solancer** [val-bubbleflat/laravel-echo-ios#2]
I've followed the steps as per your documentation but the server doesn't seem to connect at all. The server connects and disconnects immediately.

**Comment by val-bubbleflat** [comment]
Hi @solancer  ! Can I see your code and logs ? 
What server do you use ? 
I did all with this one : https://github.com/tlaverdure/laravel-echo-server

**Comment by solancer** [comment]
XcodeErrorLog.txt - https://gist.github.com/gcsawargi/0cd662d0844f4d0e516d1770066084f7

AppDelegate.swift - https://gist.github.com/gcsawargi/82dffee6eefaa0a42704321b92ac884b

UserApiMiddleware.php - https://gist.github.com/gcsawargi/7bf820ba1d5af47d99e3e689489e5bad

laravel-echo-server.json - https://gist.github.com/gcsawargi/8a8b0ff3d6e55f5ac32efcb29bea7b1b

PrivateMessageEvent.php - https://gist.github.com/gcsawargi/7c1fbc3bb5ef2e5e4b081f8e778f3f15

BroadcastServiceProvider.php - https://gist.github.com/gcsawargi/4b1d737aa997ac9a9b6ff496bd36f9a9

**Comment by solancer** [comment]
and I'm able to get authenticated through JWT and listen with HTML, JS using Echo JS lib from here https://github.com/laravel/echo

**Comment by val-bubbleflat** [comment]
@solancer 
I think you should try to replace localhost in AppDelegate.swift by the IP/full adress of your laravel-echo-server as you are on phone

**Comment by solancer** [comment]
I did that too but still the same :(

**Comment by val-bubbleflat** [comment]
Sorry but I can't find the problem... I can't replicate the connection closed by your server. I think it's more a problem from your server because your client is still active at the end.

**Comment by solancer** [comment]
You were right the problem was with the channel name apparently I had to put in private-private twice make it work.. thanks for your time man :)

**Comment by val-bubbleflat** [comment]
Perfect :) hope this module will help you :)
