### ISSUE TITLE
Emit Message

### ISSUE THREAD

**Issue by maniarali** [val-bubbleflat/laravel-echo-ios#3]
There is option of listening, but there is no documentation about emitting. 
Sorry I am new to Larvel Echo, and I don't know how to emit a message. I am implementing Chat Through Larvel echo ios. I am already able to communicate on Website, and listen those message on iOS. but don't know how to emit message. 
Thanks for any help

**Comment by val-bubbleflat** [comment]
Hi
Laravel Echo is not responsible for sending messages, your backend is. 
I think you need to send the message throught your api, and dispatch an event in your backend.
Val

**Comment by maniarali** [comment]
Thanks for the reply. I have send message using API. and listening through Larvel Echo.

**Comment by nielsezeka** [comment]
@maniarali Broadcast Whisper() can be use to send data to another client, but their was some tricks.
I reported and note in:
https://github.com/val-bubbleflat/laravel-echo-ios/issues/9 
Hope it help!
